# For more information: https://laravel.com/docs/sail
version: '3'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_backend
        ports:
            -   "8000:80"
        volumes:
            - .:/var/www
        environment:
            DB_HOST: mysql
            DB_DATABASE: laravel_database
            DB_USERNAME: laravel_user
            DB_PASSWORD: laravel_password
        depends_on:
            - mysql

    mysql:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_DATABASE: laravel_database
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
            MYSQL_ROOT_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
